In [1]:
import MNMAPI

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
a = MNMAPI.dta_api()

In [4]:
# a.initialize(os.path.join('..', '..', 'data', 'input_files_2link_fix'))

In [5]:
a.initialize(os.path.join('..', '..', 'data', 'input_files_PGH_emission'))

0L

In [6]:
link_list = pd.read_table(os.path.join('..', '..', 'data', 'input_files_PGH_emission', 'MNM_input_link'), sep = ' ')['#ID'].values.astype(np.int)

In [5]:
a.register_links(np.arange(1,5))

0L

In [7]:
a.register_links(link_list)

0L

In [8]:
a.install_cc()

0L

In [9]:
a.run_whole()

0L

In [10]:
a.get_cur_loading_interval()

17280L

In [11]:
a.get_link_inflow(np.arange(0, 30), np.arange(0, 30) + 1)

array([[0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [7. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [3.5, 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [11]:
a.get_link_tt(np.arange(0, 30))

array([[3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02],
       [3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02, 3.600036e-02, 3.600036e-02,
        3.600036e-02, 3.600036e-02],
       [6.400000e+01, 6.400000

In [ ]:
a.get_link_in_cc(4)

In [13]:
a.get_link_out_cc(4)

array([[  0. ,   0. ],
       [  1. ,   0. ],
       [  2. ,   0. ],
       [  5. ,   0. ],
       [  3. ,   0. ],
       [  4. ,   0. ],
       [  6. ,   0. ],
       [  9. ,   0. ],
       [  7. ,   0. ],
       [  8. ,   0. ],
       [ 10. ,   0. ],
       [ 12. ,   0. ],
       [ 13. ,   0. ],
       [ 11. ,   0. ],
       [ 14. ,   0. ],
       [ 15. ,   3. ],
       [ 16. ,   6. ],
       [ 17. ,   8.6],
       [ 18. ,  11.2],
       [ 19. ,  13.9],
       [ 20. ,  16.6],
       [ 21. ,  19.3],
       [ 22. ,  22. ],
       [ 23. ,  24.7],
       [ 24. ,  27.4],
       [ 25. ,  30.1],
       [ 26. ,  32.8],
       [ 27. ,  35.5],
       [ 28. ,  38.2],
       [ 29. ,  40.9],
       [ 30. ,  43.6],
       [ 31. ,  46.3],
       [ 32. ,  49. ],
       [ 33. ,  51.7],
       [ 34. ,  54.3],
       [ 35. ,  57. ],
       [ 36. ,  59.7],
       [ 37. ,  62.4],
       [ 38. ,  65.1],
       [ 39. ,  67.8],
       [ 40. ,  70.4],
       [ 41. ,  73.1],
       [ 42. ,  75.8],
       [ 43