In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import hashlib
import time
import shutil

In [3]:
MNM_nb_folder = os.path.join('..', '..', '..', 'side_project', 'network_builder')
sys.path.append(MNM_nb_folder)
python_lib_folder = os.path.join('..', '..', 'pylib')
sys.path.append(python_lib_folder)

In [4]:
from MNM_nb import *
import MNMAPI
from DODE import *

In [5]:
data_folder = os.path.join('..', '..', '..', 'data', 'input_files_2link_fix')

In [6]:
nb = MNM_network_builder()
nb.load_from_folder(data_folder)

MNM_config
MNM_pathtable


In [7]:
config = dict()
config['use_link_flow'] = True
config['use_link_tt'] = False
config['link_flow_weight'] = 1
config['link_tt_weight'] = 1
config['num_data'] = 10
config['observed_links'] = [3]
config['paths_list'] = [0, 1]

In [8]:
x_real = np.random.rand(10) * 10
data_dict = dict()
data_dict['link_flow'] = list()
for i in range(config['num_data']):
    link_df = pd.DataFrame(index = range(10), columns = [3], data = x_real + np.random.randn(10) / 10)
    data_dict['link_flow'].append(link_df)

In [9]:
pdode = PDODE(nb, config)
dode = DODE(nb, config)

In [10]:
pdode.add_data(data_dict)
dode.add_data(data_dict)

In [11]:
pdode.estimate_path_flow(init_scale = 0.1, step_size = 0.1, max_epoch = 100, adagrad = False)

Epoch: 0 Loss: 11.757367303234277
Epoch: 1 Loss: 6.105099608082027
Epoch: 2 Loss: 11.180692640740254
Epoch: 3 Loss: 6.677313105214476
Epoch: 4 Loss: 3.869331699516697
Epoch: 5 Loss: 2.486360505056447
Epoch: 6 Loss: 1.6651075479942985
Epoch: 7 Loss: 1.1924608247069366
Epoch: 8 Loss: 0.8333362800341699
Epoch: 9 Loss: 0.7168863693060363
Epoch: 10 Loss: 0.5065839896182022
Epoch: 11 Loss: 0.4768904708970232
Epoch: 12 Loss: 0.39347287008214255
Epoch: 13 Loss: 0.42071290537449213
Epoch: 14 Loss: 0.36095012490540784
Epoch: 15 Loss: 0.3371443229910015
Epoch: 16 Loss: 0.31264477287982484
Epoch: 17 Loss: 0.3331970529385715
Epoch: 18 Loss: 0.3593775470437759
Epoch: 19 Loss: 0.4989425682402042
Epoch: 20 Loss: 0.4132201401798438
Epoch: 21 Loss: 0.37806338662229155
Epoch: 22 Loss: 0.4365488345297976
Epoch: 23 Loss: 0.3804573278979297
Epoch: 24 Loss: 0.365278918748501
Epoch: 25 Loss: 0.3432329223048109
Epoch: 26 Loss: 0.3792432303568204
Epoch: 27 Loss: 0.37524321109755765
Epoch: 28 Loss: 0.32179554654

(array([5.40164715e+00, 2.70439462e+00, 6.27366121e+00, 3.14871879e+00,
        2.38527757e+00, 3.49794527e+00, 3.19509465e+00, 3.76041346e+00,
        4.47018764e+00, 1.00000000e-03, 2.20960100e+00, 1.14742017e+00,
        2.90420076e+00, 1.25127084e+00, 2.32957895e+00, 4.28185964e-01,
        4.54313930e+00, 2.08732752e+00, 4.81900554e+00, 3.70213947e+00]),
 array([0.00281628, 0.00748984, 0.00146018, 0.00193123, 0.001     ,
        0.00120962, 0.0027003 , 0.00658194, 0.01090673, 0.001     ,
        0.00229645, 0.01012391, 0.01269252, 0.00187091, 0.01138728,
        0.00368271, 0.01130361, 0.00889937, 0.00337555, 0.00224088]))

In [12]:
dode.estimate_path_flow(init_scale = 0.1, step_size = 0.1, max_epoch = 100, adagrad = False)

Epoch: 0 Loss: 11.803197113728075
Epoch: 1 Loss: 2.8256341277673656
Epoch: 2 Loss: 1.2936437767839513
Epoch: 3 Loss: 0.5490860891657268
Epoch: 4 Loss: 0.40393733242768476
Epoch: 5 Loss: 0.3302143070763968
Epoch: 6 Loss: 0.35228404176499595
Epoch: 7 Loss: 0.344429351560066
Epoch: 8 Loss: 0.35191967363773663
Epoch: 9 Loss: 0.3295708873021804
Epoch: 10 Loss: 0.3179565886912724
Epoch: 11 Loss: 0.32322197698013305
Epoch: 12 Loss: 0.33412861744175815
Epoch: 13 Loss: 0.31268030619491377
Epoch: 14 Loss: 0.34835948222591745
Epoch: 15 Loss: 0.356549259621039
Epoch: 16 Loss: 0.31419312321664605
Epoch: 17 Loss: 0.32239106599408995
Epoch: 18 Loss: 0.29268271171860205
Epoch: 19 Loss: 0.31593018224636377
Epoch: 20 Loss: 0.31187296149224897
Epoch: 21 Loss: 0.3112993497162563
Epoch: 22 Loss: 0.314628231721596
Epoch: 23 Loss: 0.33426551101274427
Epoch: 24 Loss: 0.3263976967004353
Epoch: 25 Loss: 0.35158624110813463
Epoch: 26 Loss: 0.2926200451181104
Epoch: 27 Loss: 0.3243952483380793
Epoch: 28 Loss: 0.3

array([3.52609934, 4.58479025, 3.90191907, 5.51168109, 5.83482026,
       0.01207602, 2.24052631, 4.71973635, 2.64941212, 1.81314136,
       0.37650081, 2.97249126, 1.92548783, 2.22222206, 1.89524841,
       0.86851698, 3.46995914, 3.16587885, 1.14838629, 7.37887042])